version: "3.8"

services:
  ltxv-pod:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./cache:/app/.cache # Persist model cache
      - ./videos:/app/videos # Output videos
    environment:
      - PORT=5000
      - HF_HOME=/app/.cache/huggingface
      - TRANSFORMERS_CACHE=/app/.cache/huggingface/transformers
      - HF_DATASETS_CACHE=/app/.cache/huggingface/datasets
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
